# Generated by Django 5.2.3 on 2025-07-02 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapeexpectations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('vertical', models.CharField(choices=[('GTT', 'GTT'), ('H&I', 'H&I'), ('Banking', 'Banking'), ('FS', 'FS'), ('Others', 'Others')], max_length=10)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='grapeexpectations.register')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeImage',
            fields=[
                ('resumeid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='resumes/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_images', to='grapeexpectations.register')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grapeexpectations.register')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grapeexpectations.question')),
            ],
            options={
                'unique_together': {('empid', 'question')},
            },
        ),
    ]
